hapi:
  fhir:
    tester:
        -
          id: home
          name: Local Tester
          server_address: 'http://localhost:8080/fhir'
          refuse_to_fetch_third_party_urls: false
          fhir_version: R4

server:
  port: 8082

authorized_roles: clin_administrator

keycloak:
  auth-server-url: http://localhost:8081/auth/
  realm: master
  resource: fhir-console
  public-client: true
  principal-attribute: preferred_username

bio:
  keycloak:
    auth-server-url: http://localhost:8081/auth/
    realm: master
    audience: fhir-console