name: Publish Image Using Latest Tag

on:
  push:
    branches:
      - main

jobs:
  push:
    name: Publish Image using Latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push the image on the registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/fhir-console
          tag_format: "latest"