name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
      - name: Publish the image
        run: ./push_image.sh
